<<<<<<< HEAD
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Daily',
  description: 'Flashcard',
=======
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
>>>>>>> f43e601 (chore: basic main menu)
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
